### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by jayathu** [modesttree/Projeny#31]
Hi,

First off, thanks so much for putting together this awesome project. I've been looking for a solution like this for a long time. If only I could run through your sample project set up walkthrough, that would be really awesome. Right now I am stuck at the very initial stage when you run prj --init to set up symlinks to folders. 

I followed every single set up instruction as laid out in your read me. And I have downloaded the sample project as well. I have also set up all the path variables properly. Now I am at a point where I need to run prj --init and I am getting an 'Import Error" : DLL Load failed: The specified module could not be found. 

I can't figure out why and what's causing this issue. Do you have any clues?

Btw, I am running Python 3.5 and Visual Studios 2015. And its a Surface Pro with Windows 10 OS.

Thanks,
Jay

**Comment by svermeulen** [comment]
Hey, no problem, hopefully you can get it working and benefit from it.  We've been using various versions of it internally at our company for years now.

I'm assuming you're running directly from the python source since you mentioned python, is that right?  You could also try running the exe build by running the windows installer.  Would be interesting to hear if that fixes it.

Is there a PrjLog.txt file in the directory you're running?

**Comment by jayathu** [comment]
I'll try with the windows installer and let you know. Thanks!

**Comment by arthuronoszko** [comment]
Hi! I would really like to try this, but I get stuck with prj --init as @jayathu got.

I ran web installer for Python 3.6 and the ProjenyInstaller 0.3.6. When I type prj --init I get the following error:

`Traceback (most recent call last):
  File "boot_common.py", line 46, in <module>
  File "C:\Utils\Python\Python32-34\lib\ctypes\__init__.py", line 7, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: The specified module could not be found.) 'C:\\Program Files (x86)\\Projeny\\Bin\\Data\\Prj\\_ctypes.pyd'
Traceback (most recent call last):
  File "Prj.py", line 15, in <module>
  File "C:\Projects\Projeny\Source\mtm\util\SystemHelper.py", line 13, in <module>
  File "C:\Projects\Projeny\Source\mtm\util\JunctionUtil.py", line 1, in <module>
  File "C:\Utils\Python\Python32-34\lib\ctypes\__init__.py", line 7, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: The specified module could not be found.) 'C:\\Program Files (x86)\\Projeny\\Bin\\Data\\Prj\\_ctypes.pyd'`

Can you please help me? I think that Projeny could really help our product, so I am very eager to test it :)

BR
Arthur

**Comment by svermeulen** [comment]
If you run it from source (see installation instructions) it should work.  This seems to be an issue with the way we're building the python as an exe.
